# Generated by Django 3.1.2 on 2020-11-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerImages',
            new_name='BannerImage',
        ),
    ]
