# Generated by Django 3.1.2 on 2020-11-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_images', '0002_auto_20201104_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, max_length=5, null=True, upload_to='banner_images/'),
        ),
    ]
