# Generated by Django 3.1.2 on 2020-11-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_images', '0003_auto_20201105_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
