# Generated by Django 3.1.2 on 2020-11-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hours',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
