# Generated by Django 3.1.2 on 2020-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dayClose',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='dayOpen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='hourClose',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='hourOpen',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
